FROM php:apache

# Install debug tools
RUN apt update \
    && apt install -y netcat-openbsd \
    && apt install -y default-mysql-client 

# Install MySQLi extension
RUN docker-php-ext-install mysqli

# Copy local files to container
COPY . /var/www/html/