################################################################
# For local development only, to debug Kubernetes
################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MYSQL_DATABASE: "user_management"
  MYSQL_SERVER_URL: "backend-db-service"
  MYSQL_PORT: "3306"

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  MYSQL_USER: "cm9vdA==" # echo -n "root" | base64
  MYSQL_PASSWORD: "MTIzNDU=" # echo -n "12345" | base64

---

################################################################
# backend-db
################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db-deployment
  labels:
    app: backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
      - name: backend-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MYSQL_DATABASE
        volumeMounts:
        - name: backend-db-volume
          mountPath: /var/lib/mysql
        - name: backend-db-init-volume
          mountPath: /docker-entrypoint-initdb.d/init.sql
      volumes:
      - name: backend-db-volume
        persistentVolumeClaim:
          claimName: backend-db-pvc
      - name: backend-db-init-volume
        configMap:
          name: backend-db-init-sql

---

apiVersion: v1
kind: Service
metadata:
  name: backend-db-service
spec:
  selector:
    app: backend-db
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30101

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-db-pv
spec:
  capacity:
    storage: 512Mi 
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /run/desktop/mnt/host/c/Users/Ombar/pogo
  storageClassName: ""
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db-pvc
spec:
  volumeName: backend-db-pv
  resources:
    requests:
      storage: 512Mi 
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-db-init-sql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS user_management;
    USE user_management;

    -- Create users table
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL,
        email VARCHAR(100) NOT NULL
    );

    -- Insert sample data
    INSERT INTO users (username, email) VALUES
        ('Alan', 'alan@cstj.qc.ca'),
        ('Bob', 'bob@cstj.qc.ca'),
        ('Carl', 'carl@cstj.qc.ca');

---

################################################################
# backend
################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: php-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MYSQL_SERVER_URL
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MYSQL_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MYSQL_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100

---

################################################################
# frontend
################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: php-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

